const MISSING_SPEC*: string = "Missing specification."
const MISSING_STRUCTURE*: string = "Missing structure."
const SPEC_NOT_AVAILABLE*: string = "Spec not available."
const CUSTOM_SPEC_NOT_FOUND*: string = "Custom spec not found."
const STRUCTURE_NOT_FOUND*: string = "Structure file not found."
const MULTIPLE_SPECS*: string = "Multiple specs have been given."
const STRUCTURE_MATCH_ERROR*: string = "An unexpected key has been found in the given structure."